name       : budgie-user-indicator-redux-applet
version    : 1.0.1
release    : 2
source     :
    - https://github.com/EbonJaeger/budgie-user-indicator-redux/archive/refs/tags/v1.0.1.tar.gz : 3e5ed4d81b4fddd15b7388a6b8dce42169e1b4673df8aa00bbafa65cdb145f08
homepage   : https://github.com/EbonJaeger/budgie-user-indicator-redux
license    : GPL-2.0-or-later
component  : desktop.budgie
summary    : Manage your user session from the Budgie panel
description: |
    Recreates the old user indicator applet functionality of Budgie Desktop to manage your user session directly from the panel menu, instead of opening the Power Dialog.
builddeps  :
    - pkgconfig(accountsservice)
    - pkgconfig(budgie-1.0)
    - pkgconfig(gee-0.8)
    - sassc
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
